### ISSUE TITLE
[1pt] Create basic structure for Missions - Setup

### ISSUE THREAD

**Issue by kalbek** [kalbek/react-group-project#22]
## [Link to PR](https://github.com/kalbek/react-group-project/pull/34)
- Create a route and a view component. Use `<NavLink />` for the page navigation links and style active class to indicate which section/page the user is currently on (underline active navigation link).
- Create a directory for all Redux state slice files.

**Comment by tsheporamantso** [comment]
https://github.com/kalbek/react-group-project/pull/34
